### ISSUE TITLE
Logos als Vektorgraphik

### ISSUE THREAD

**Issue by RDBloese** [thesaurus-linguae-aegyptiae/tla-web#121]
BBAW und SAW Logos sind als Rastergrafik hinterlegt und je anch Anzeigemedium unscharf. 
-> Vektorgrafik

**Comment by dwerning** [comment]
Welche Daten-Formate wären da geeignet? Von einigen liegen mir EPS-Dateien vor.

**Comment by RDBloese** [comment]
SVG-Format wäre m.E. nach am besten

**Comment by dwerning** [comment]
Kann man das konvertieren: EPS > SVG?

**Comment by RDBloese** [comment]
Müsste ich probieren, bin mir da nicht sicher. Könnten Sie mir die EPS per Mail schicken?

**Comment by dwerning** [comment]
Anfrage bzgl. echter Vektorgraphik-Formate an BBAW läuft.

**Comment by RDBloese** [comment]
Müsste ich probieren, bin mir da nicht sicher. Könnten Sie mir die EPS per Mail schicken?

**Comment by RDBloese** [comment]
PNG gegen SVG getauscht.
