### ISSUE TITLE
Suche-Seite: Default-Werte welche Lemmaliste

### ISSUE THREAD

**Issue by dwerning** [thesaurus-linguae-aegyptiae/tla-web#135]
(a) per default
* Hiero: ckecked
* Demot: unchecked
![grafik](https://user-images.githubusercontent.com/33833393/126773327-9a90fc77-76f7-42ab-80b9-2088637d21f5.png)

(b) Es darf kein Zustand entstehen, in dem beide Boxes unchecked sind.
Daher: Wenn hiero gecheckt, Demotic aber ungecheckt, und man schaltet hiero weg, soll automatisch demotic gecheckt werden;
analog: Wenn demotic gecheckt, hiero aber ungecheckt, und man schaltet demotic weg, soll automatisch hiero gecheckt werden

**Comment by simondschweitzer** [comment]
Das entspricht nicht der Referenz https://github.com/thesaurus-linguae-aegyptiae/tla-dev-doc/blob/master/design/wireframes/02a_erweiterte_suche_wort.txt
Danach sollte es nur "Ägyptisch", d.h. "Hieroglyphisch/Hieratisch" sein. (Hier ist wohl nicht der Ort, die sinnvollen Argumente für diese Entscheidung zu wiederholen, oder?)

**Comment by dwerning** [comment]
dann: 
- Hiero: ckecked
- Demot: unchecked
