### ISSUE TITLE
Vereinheitlichung Editorennamen

### ISSUE THREAD

**Issue by LutzPopko** [thesaurus-linguae-aegyptiae/tla-web#206]
Die Ausgabe der Namen der Editoren sollte vereinheitlicht werden. Im Prototyp sind bspw. die Vornamen von Herrn Quack ausgeschrieben, alle anderen abgekürzt (nachzuprüfen bspw. über die Belege von Lemma-ID 148360). Aus Platzgründen ist es besser, wenn alle Vornamen abgekürzt werden.

**Comment by simondschweitzer** [comment]
Das gibt insofern Probleme, als die Nutzer dann nicht wissen, wer mit "A. Weber" gemeint ist: Anke oder Anja.

**Comment by LutzPopko** [comment]
Dann umgekehrt alle ausschreiben. Aber mal so und mal so ist uneinheitlich.

**Comment by simondschweitzer** [comment]
> Vielleicht ist es technisch realisierbar A. Weber anzuzeigen, den vollen Namen bei Mouseover im Kästchen einzublenden?

Das gibt auch Probleme: 1) Mouseover ist eine Lösung für Desktops, passt aber schlecht für mobile Endgeräte. Insofern geht das nicht mit dem responsiven Design konform. 2) Wenn man nur bei A. Weber die Disambiguierung einführt, müsste man einen einzelnen Sonderfall betreuen. Evtl. kommt später noch einer dazu, was man aber nicht absehen kann. Das ist schlecht zu warten. Wenn schon müsste man das für alle Namen einführen, was aber wegen Punkt 1 problematisch ist.

**Comment by LutzPopko** [comment]
Woher bekommt denn die Webanzeige des TLA überhaupt ihre Information? Auch im BTS wird Herrn Quacks Name im Autorenfeld des entsprechenden Textes und Objekts mit ausgeschriebenen Vornamen angezeigt, während bei den sonstigen Autoren im Autorenfeld immer nur ein Vornamenskürzel steht. Wenn man (oder zumindest ich) im BTS die Liste der User öffne, sind dagegen alle Vornamen ausgeschrieben. Das heißt für mich, dass es im Hintergrund des BTS einen Automatismus gibt, der weiß, was Vor- und Nachnamen sind und der Vornamen entsprechend abkürzt -- nur eben bei Herrn Quack (und vielleicht noch anderen?) nicht. Die Ursache für dieses Anzeigephänomen sollte man also zuerst dort suchen.
