### ISSUE TITLE
Privacy Policy content

### ISSUE THREAD

**Issue by dwerning** [thesaurus-linguae-aegyptiae/tla-web#30]
- recheck with Datenschutzbeauftragen BBAW

**Comment by dwerning** [comment]
email Datenschutzbeauftragte:r 11.11.2021

**Comment by dwerning** [comment]
überarbeitete Version bei Datenschutzbeauftragtem/r

**Comment by schnoepf** [comment]
Einbindung https://dschutz.bbaw.de müsste doch reichen...

**Comment by dwerning** [comment]
Hinweis Facebook, Twitter checken

**Comment by dwerning** [comment]
Hinweis Facebook, Twitter bei _reiner Verlinkung_ lt. Datenschutzbeauftragtem/r nicht nötig.

**Comment by dwerning** [comment]
Abhänig auch von 
- #392

**Comment by dwerning** [comment]
Final ohne Cloudflare
