### ISSUE TITLE
Belegstellenliste: case-Permutationen gruppiert als solche markieren

### ISSUE THREAD

**Issue by dwerning** [thesaurus-linguae-aegyptiae/tla-web#310]
SSch
> Sätze mit Lesevarianten werden bei Belegmengen leider mehrfach aufgeführt. Beispiel: <https://tlabeta.bbaw.de/lemma/100680> habe "Instanzen in 4 Sätze". Klickt man jedoch auf <https://tlabeta.bbaw.de/search/sentence?tokens[0].lemma.id=100680>, muss man feststellen, dass der zweite und der dritte Beleg für dieses Verb identisch sind. Die beiden vermeintlichen Belege stammen aus genau einem Satz, welcher jedoch zwei Lesevarianten besitzt. Das Verb, deren Belege hier aufgelistet werden, steht aber außerhalb der Lesevariante. Insofern ist der Beleg fälschlicherweise verdoppelt.

**ToDo**
Varianten rauszufiltern, weil die Varianz 'außerhalb' des relevanten Bereichs des gesuchten Lemmas ist, ist sicher kaum (zeiteffizient) umsetzbar.
Eine bessere Markierung der Zugehörigkeit würde hier schon helfen.

Vgl. dazu auch
#219

**Comment by simondschweitzer** [comment]
Bei den Belegen die Varianten rauszufiltern, ist gar nicht so schwer. Man kann einfach die Token-IDs berücksichtigen.

**Comment by dwerning** [comment]
Obsolet
