### ISSUE TITLE
Satzpfade: Pfad-Elemente in "〈____〉" ausblenden

### ISSUE THREAD

**Issue by dwerning** [thesaurus-linguae-aegyptiae/tla-web#324]
LP
> Zwecks Lokalisierung ist bei den Belegstellen im Prototyp der gesamte Pfad angegeben, also bspw.:
> 〈Projekt "Digital Heka", Universität Leipzig〉 >> Magische Papyri Neues Reich >> 〈Komplette Handschriften〉 >> pLeiden I 348 = AMS 26a >> Spruch 32 
> Hier stehen einige Teile des Pfades zwischen spitzen Klammern. Diese waren ein Hilfsmittel des Altprojektes, um in der Belegstellenanzeige des alten TLA Pfadteile auszublenden, die man als überflüssig erachtete, bspw. um Doppler zu vermeiden, wenn Objekt und Text denselben Namen hatten. Alles zwischen spitzen Klammern wurde zumindest in der Belegstellenanzeige nicht angezeigt. Zum Vergleich: So sieht der betreffende Pfad im alten TLA (https://aaew.bbaw.de/tla/servlet/GetWcnRefs?u=guest&f=0&l=0&ll=*92580&wt=y&lr=0&mo=1&db=0&of=378) aus:
> Thesaurus Linguae Aegyptiae, Magische Papyri Neues Reich, pLeiden I 348, Spruch 32
> Es bliebe evtl. zu diskutieren, ob wir das zukünftig wieder so händeln. Aktuell ist aber kein Anklicken des Cotextes möglich, und zum Gesamttext kommt man auch nicht. Daher ist aktuell die Anzeige des vollständigen Pfades in meinen Augen sinnvoll, damit man sich orientieren kann. Daher frage ich mich, ob es beim aktuellen Stand des TLA nicht sinnvoller ist, die spitzen Klammern selbst auszublenden, dass also das zwischen diesen Klammern Stehende sichtbar bleibt, aber die Klammern selbst eben unsichtbar werden.

**Befund**
Einige Pfadteile-Namen sind als Ganzes(!) in spitzen Klammern gesetzt, z.B.
![grafik](https://user-images.githubusercontent.com/33833393/181205632-bbac0177-f492-47ce-afa6-9795df17ccff.png)
(Satz ID IBUBd8hvaZXFQEg2hl7UYgsCWPw)

**ToDo**
Pfadteile die mit spitzen Klammern beginnen und enden(!) (Unicode: \u2329 \u232A) ausblenden.

Vgl. auch ähnliches Issue #358.

**Comment by dwerning** [comment]
Erledigt:

    Für Pfadteile, die mit spiter Klammer anfangen und aufhören, weden die Ikons ausgeblendet
    Feature-umSetzung zu 

    https://github.com/thesaurus-linguae-aegyptiae/tla-web/issues/358 blendet alle Teile im label aus, die in spitzen Klammern sind.

Problem: Sonderfälle wie "〈aaa〉bbb〈ccc〉" werden dann angezeigt, aber ohne Ikon. Kommt das vor?

**Comment by dwerning** [comment]
SSch
> augenscheinlich wurden alle Einträge, die sich komplett in spitzen Klammern befinden, aus den Pfaden entfernt, sodass nur noch kurze Pfade erscheinen. Das ist aus mehreren Gründen kontraproduktiv:
Ein Pfad bildet die Hierarchie der Elemente ab. Löscht man Zwischenglieder, fehlen diese in der Betrachtung, sodass der Pfad, der qua definitionem eine Darstellung der Hierarchie ist, seiner Aufgabe nicht mehr gerecht wird.
Fehlen Zwischenglieder, sind sie nicht mehr anklickbar, was ja künftig angestrebt werden wird, um Belegstellen und Texthierarchie noch besser zu verzahnen.
Unterschiedliche Pfade sehen nach dem Herauslöschen identisch aus, was ich in einer Mail um 10:26 notiert habe. Das irritiert den Nutzer.
In dieser Form steht das Ergebnis etwas zwischen den Welten. Entweder man geht den spitze-Klammern-löschen-Schritt konsequent weiter (dann erzeugt man aber keine Pfade, sondern reine Benamungen; hier wären dann auch die Icons, die auf die Hierarchieglieder referieren, zu tilgen) oder man behält den Pfadcharakter bei (dann darf man aber keine Zwischenglieder löschen).
Bitte konsequent entweder die Benamungsidee oder die Pfadidee umsetzen!

**Comment by dwerning** [comment]
Beispiel durch Ausblendung scheinbar doppelter Pfad, Satz ID IBUBd45InxwBTkwAkDCVfbAGGjI

**Comment by dwerning** [comment]
SSch
> hier ein Lösungsvorschlag auf Frontendebene:
Wenn Anzahl der Pfade > 1, dann gib nur unterschiedliche Pfadstrings raus.

**Comment by dwerning** [comment]
Weiterer Fall
DT
> wenn ein Text über mehrere Wände verteilt ist, erscheint die Angabe der Belegstelle mehrfach, z.B. bei Padihorresnet,
s. https://tlabeta.bbaw.de/search/sentence?tokens[0].lemma.id=55740
Um das zu verhindern, müsste ich wohl die spitzen Klammern um die Namen der "ObjectPart" entfernen - LP hat, wenn ich unser Freitag-Gespräch richtig erinnere, einen entsprechenden Fall so gelöst - was ich aber ungern tun würde. Gibt es noch eine andere Lösung?

**Comment by dwerning** [comment]
Siehe dazu nun auch #429

**Comment by dwerning** [comment]
Damand doch da?

Umsetzung war schon mal da:
https://github.com/thesaurus-linguae-aegyptiae/tla-web/pull/381/commits/152784b880b2dd315d9d0567bc886f4333347369

**Comment by LutzPopko** [comment]
Nur zur Info: Im Eingangspost kannst Du den letzten Absatz, alles ab "Es bliebe evtl. zu diskutieren (...)", ignorieren. Das war vor dem Hintergrund der allerersten Online-Version von TLA 2.0 geschrieben, der noch keine Volltextanzeige konnte.

> LP
> 
> > Zwecks Lokalisierung ist bei den Belegstellen im Prototyp der gesamte Pfad angegeben, also bspw.:
> > 〈Projekt "Digital Heka", Universität Leipzig〉 >> Magische Papyri Neues Reich >> 〈Komplette Handschriften〉 >> pLeiden I 348 = AMS 26a >> Spruch 32
> > Hier stehen einige Teile des Pfades zwischen spitzen Klammern. Diese waren ein Hilfsmittel des Altprojektes, um in der Belegstellenanzeige des alten TLA Pfadteile auszublenden, die man als überflüssig erachtete, bspw. um Doppler zu vermeiden, wenn Objekt und Text denselben Namen hatten. Alles zwischen spitzen Klammern wurde zumindest in der Belegstellenanzeige nicht angezeigt. Zum Vergleich: So sieht der betreffende Pfad im alten TLA (https://aaew.bbaw.de/tla/servlet/GetWcnRefs?u=guest&f=0&l=0&ll=*92580&wt=y&lr=0&mo=1&db=0&of=378) aus:
> > Thesaurus Linguae Aegyptiae, Magische Papyri Neues Reich, pLeiden I 348, Spruch 32
> > Es bliebe evtl. zu diskutieren, ob wir das zukünftig wieder so händeln. Aktuell ist aber kein Anklicken des Cotextes möglich, und zum Gesamttext kommt man auch nicht. Daher ist aktuell die Anzeige des vollständigen Pfades in meinen Augen sinnvoll, damit man sich orientieren kann. Daher frage ich mich, ob es beim aktuellen Stand des TLA nicht sinnvoller ist, die spitzen Klammern selbst auszublenden, dass also das zwischen diesen Klammern Stehende sichtbar bleibt, aber die Klammern selbst eben unsichtbar werden.
>

**Comment by LutzPopko** [comment]
> Weiterer Fall DT
> 
> > wenn ein Text über mehrere Wände verteilt ist, erscheint die Angabe der Belegstelle mehrfach, z.B. bei Padihorresnet,
> > s. [https://tlabeta.bbaw.de/search/sentence?tokens[0].lemma.id=55740](https://tlabeta.bbaw.de/search/sentence?tokens%5B0%5D.lemma.id=55740)
> > Um das zu verhindern, müsste ich wohl die spitzen Klammern um die Namen der "ObjectPart" entfernen - LP hat, wenn ich unser Freitag-Gespräch richtig erinnere, einen entsprechenden Fall so gelöst - was ich aber ungern tun würde. Gibt es noch eine andere Lösung?
> 
> IBUBdyR4Jr6aEk2kp6H99wjAWr0
> 
> ![grafik](https://user-images.githubusercontent.com/33833393/188452567-e48f5716-15f0-42e2-af2d-7c2d0332dc2f.png)

Dieser Fall ist tatsächlich etwas anders: Frau Topmann hat im Grab des Padihorresnet jeden Raum auf die einzelnen Wände heruntergebrochen und diese tlw. auch noch in Wandhälften. D.h. jede einzelne Wand/-hälfte ist ein eigener ObjectPart. In anderen Räumen mag das vielleicht sinnvoll sein (habe ich nicht weiter durchdacht), aber hier eher weniger. Hier hat sie nur einen einzigen Text aufgenommen, der sich eben über alle Wände erstreckt, und deswegen hat sie denselben Text mit allen betreffenden ObjectParts verknüpft. Aus meiner Perspektive wäre es sinnvoller gewesen, wenn sie bei diesem Raum die Objekt- und Objektteil-Hierarchie nur bis zur Ebene des einzelnen Raumes geführt hätte, daran dann den Text gehängt und die konkrete Verteilung, welcher Textteil sich auf welcher Wand befindet, allenfalls mithilfe von Annotationen (alte Lösung) bzw. #loc: __#-Taggings (neue Lösung), markiert.
