### ISSUE TITLE
Language switching does not work

### ISSUE THREAD

**Issue by dwerning** [thesaurus-linguae-aegyptiae/tla-web#37]
- to do: file with English strings needs to be renamed "-en", like "-de" file

**Comment by dwerning** [comment]
DE/EN-Switch funktioniert noch nicht.

**Comment by dwerning** [comment]
to do: file with English strings needs to be renamed "-en", like "-de" file
oder: Code anpassen

**Comment by JKatzwinkel** [comment]
Anwendung der Sprachauswahl auf Basis einer Session-Variable wird in https://github.com/thesaurus-linguae-aegyptiae/tla-web/blob/master/src/test/java/tla/web/mvc/SearchPageTest.java#L181-L187 sichergestellt, falls doch irgendwo noch unerwartetes Verhalten auftritt, wären genauere Infos zur Reproduktion des vermeintlichen Fehlers nötig.

**Comment by dwerning** [comment]
Bug-Beschreibung:
Sprache dauerhaft auf DE, Umschaltung auf EN über Button oder über URL-Parameter ändern nichts.

**Comment by dwerning** [comment]
Nachfolge-Bug (nocht-kritisch) #131
