### ISSUE TITLE
Serverzertifikate für neue URLs beantragen

### ISSUE THREAD

**Issue by RDBloese** [thesaurus-linguae-aegyptiae/tla-web#477]
Serverzertifikate für tla.digital und thesaurus-linguae-aegyptiae beantragen um https Verbindung zu ermöglichen.

**Comment by RDBloese** [comment]
Antragsdokumente wurden erstellt und sind an Herrn Lange (IT) geschickt worden. Warte auf Rückmeldung

**Comment by dwerning** [comment]
Erledigt.
