### ISSUE TITLE
Suchseite: Unicode keyboard missing on Chrome/Safari

### ISSUE THREAD

**Issue by dwerning** [thesaurus-linguae-aegyptiae/tla-web#488]
AS
> The tiny keyboard that I see in Safari to enter Unicode in the search does not appear in Chrome (although my Chrome might not be up-to-date)

**Comment by cvertan** [comment]
CV
getestet auf iOS 15.6.5  funktioniert auf
Safari 15.6.5 und Chrome 106.0.5249.92

Auch auf Windows 11 chome Version 106.0.5249.119

funktioniert auf aleen 3 einwandfrei

**Comment by dwerning** [comment]
Auch in browserstack nicht in Chrome/MacOS(bigsur) verifizierbar
