### ISSUE TITLE
Search logic: Regular Expression search does not work

### ISSUE THREAD

**Issue by dwerning** [thesaurus-linguae-aegyptiae/tla-web#57]

**Comment by simondschweitzer** [comment]
Die Frage ist, ob denn das überhaupt gewünscht ist. Die RegEx-Zeichen beißen sich ja mit den Umschriftzeichen. So denkt ein Ägyptologe bei mrw.t nicht an den RegEx-Punkt. Insofern dürfte RegEx nicht als Default eingestellt sein, sondern es müsste einen zusätzlichen Knopf geben, RegEx einzuschalten. Oder es müsste RegEx mit anderen Zeichen implementiert werden, wie es Herr Seidlmayer beim alten TLA gemacht hat.
Ferner müsste man sich anschauen, wie häufig RegEx benutzt wird. Ich kenne nur eine einzige TLA-User-Bubble, in der RegEx verwendet wird. Fast alle Nutzer verwenden es nicht. (Insofern muss man hier eine Kosten-Nutzen-Rechnung aufmachen.)
Schließlich nutzen moderne Searchinterfaces eher eine fuzzy search als RegEx, sodass eine solche auch hier angedacht war; denn diese hat den Vorteil, dass die Nutzer da abgeholt werden, wo sie sich normalerweise bewegen: in Googlesuchen nutzen sie keine RegEx, sondern finden auch Treffer, wenn die Eingabe leicht abweicht. D.h. eine Fuzzysearch könnte bei einem mrwt unser mrw.t finden.

**Comment by dwerning** [comment]
Ja, die Möglichkeit einer Nicht-fuzzy-RegEx-Suche ist gewünscht;
zum möglichen Gestaltung und offenen Konzeptionsfragen einer Fuzzy Search vgl. https://github.com/thesaurus-linguae-aegyptiae/tla-web/discussions/128

**Comment by simondschweitzer** [comment]
Zur Entscheidung fuzzy statt Regex vgl. https://github.com/thesaurus-linguae-aegyptiae/tla-dev-doc/blob/master/design/wireframes/02a_erweiterte_suche_wort.txt

**Comment by dwerning** [comment]
hier noch die Hinweise zur RegEx-artigen Umsetzung im alten TLA: https://aaew.bbaw.de/tla/servlet/S04?f=h003
RegEx-Subset und Abwandlung:
- belibiges, einzelnes Zeichen: RegEx: "." => TLA-alt: "§" (denn "." ist Teil von Lemma-Transkriptionen) (RegEx ".*" wird im TLA-alt automatisch rechts ergänzt, d.h. "jm" findet auch "jmn")
- Wortende: RegEx "\\>" => TLA-alt: "$"  (Hintergrund: Verhalten im TLA-alt ist als würde RegEx ".*" automatisch rechts im Suchstring ergänzt, d.h. "jm" findet auch "jmn")
- Wortanfang: RegEx "\\<"  => im TLA-alt per default links ergänzt
- Alternative Zeichen: RegEx/Tla-alt "[   ]" (m.W., sinnvoller Weise, _ohne_ Erlaubnis von Zeichenbereichen mit "-")
- Alternative Nicht-Zeichen: RegEx/Tla-alt "[^   ]" 
- Optional einmal = 0 oder 1 Mal: RexEx/TLA-alt "?"
- Mindestens = 1 oder mehr Mal: RexEx/TLA-alt "+"
- Optional viele = 0 oder mehr Mal: RexEx/TLA-alt "\*"

Noch hinzuzufügen:
- "\\\*" (wirklich "*")
- "\\?" (wirklich "?")
- "\\[" und "\\]" (wirklich "[   ]")
Zu sondieren: RegEx "(   |  )"-Konstruktion. (Kommen "(  )" in Lemmata vor? In Textwort-Transliterationen sicherlich.)
