### ISSUE TITLE
Variantenzählung aus der Zitation/aus dem Nachschlagen herausnehmen

### ISSUE THREAD

**Issue by dwerning** [thesaurus-linguae-aegyptiae/tla-web#573]
Stand:
- Variantenzählung ist nicht stabil nach Änderungen bzgl. der `case`-Anzahl in Sätzen.
- Zitationsweise nicht stabil, wenn `case`-loser Satz in Satz mit `case` gewechselt wird -- oder umgekehrt.

BTW: Ausspielung der `case`-Indizes wird von hex mit pertiellem 0-padding auf dez. ohne 0-padding umgestellt.
- https://github.com/thesaurus-linguae-aegyptiae/tla-datentransformation/issues/118

**Comment by RDBloese** [comment]
Umstellung Hex zu Dez wird in Datentransformation bearbeitet.
-https://github.com/thesaurus-linguae-aegyptiae/tla-datentransformation/issues/134

**Comment by dwerning** [comment]
Auch eine URL muss ohne "-01" erreichbar sein, um aus Rohdaten generierte Links zu bedienen.

**Comment by dwerning** [comment]
Erledigt.
- Beim Nachschlagen führen http://localhost:8080/sentence/IBUBd3fokT5z2kxRvVBXwpDsmB0 und http://localhost:8080/sentence/IBUBd3fokT5z2kxRvVBXwpDsmB0-00 zum selben Ergebnis.
- Zitation ohne die Varianen-Suffix "-00", "-01", ...; entsprechende Warnung
