### ISSUE TITLE
Lemma-Zitation: Umschrift ohne Unicode-Fonteinstellung

### ISSUE THREAD

**Issue by dwerning** [thesaurus-linguae-aegyptiae/tla-web#607]
LP
> ![Timeout-Problem_1](https://github.com/thesaurus-linguae-aegyptiae/tla-web/assets/33833393/90d02357-4293-4aee-9070-e8ac55108996)

**Comment by RDBloese** [comment]
Bei mir wird es korrekt dargestellt https://tla.digital/lemma/32510 Liegt obiges Verhalten ggf. an einem (temporären) Serverfehler bei der Auslieferung und eben keine Umschrift ohne Unicode-Fonteinstellung?

**Comment by dwerning** [comment]
`<span class="bbaw-libertine">` o.ä. fehlt um den Namen herum

**Comment by LutzPopko** [comment]
Ich entdecke gerade, dass dieser Fehler nur auftaucht, wenn ich den TLA mit Google Chrome benutze (Version 117.0.5938.63 (Offizieller Build) (64-Bit)). In Firefox ist die Anzeige korrekt.

**Comment by dwerning** [comment]
Fonteinstellung eingefügt
