### ISSUE TITLE
Belegstellenseite: Highlightening of occurrences

### ISSUE THREAD

**Issue by LutzPopko** [thesaurus-linguae-aegyptiae/tla-web#66]
Is it possible to highlight the searched token in the list of occurrences? This would be helpful especially if the translation of the indivdual transliteration differs too much from the standard transliteration in the BWL.

**Comment by dwerning** [comment]
Dazu gab es schon einmal einen Farbcheck mit Rot-Grün-schwachen Probanden. ... zu suchen ... Das war im Prototyp implementiert. Aber ist im Eval-Prototyp unerklärlicherweise verschwunden.

**Comment by dwerning** [comment]
Siehe hier: https://github.com/thesaurus-linguae-aegyptiae/tla-webdesign-prototype/issues/60
