### ISSUE TITLE
Suchseite: Auswahl-Art der Übersetzungssprache

### ISSUE THREAD

**Issue by simondschweitzer** [thesaurus-linguae-aegyptiae/tla-web#68]
Auswahlmenu statt Checkboxen, vgl. https://github.com/JKatzwinkel/tla-dev-doc/raw/master/design/wireframes/02a_erweiterte_suche_wort.png

**Comment by dwerning** [comment]
Bitte als horizontale Folge von _Radio-Buttons_ implementieren.

**Comment by dwerning** [comment]
erledigt
