### ISSUE TITLE
Bezeichnungen: Suche

### ISSUE THREAD

**Issue by simondschweitzer** [thesaurus-linguae-aegyptiae/tla-web#69]
Viele der Bezeichnungen sind ungenau und/oder ad-hoc-Bezeichnungen und müssen korrigiert werden. Im einzelnen:
de-prepositionale Nisbe → Nisben von Präpositionen
de-nominale Nisbe → Nisben von Substantiven
de-prepositionales Adverb → Präpositionaladverbien
Artifakt-Namen → Namen von Sachen
Götter-/Göttinnenname → Götternamen
Königs-/Königinnenname → Königsnamen
Organisationsname → Namen von Institutionen
Interrogativ-Pronomen → Interrogativpronomina
göttliches Epitheton → Epitheta von Göttern
königliches Epitheton → Epitheta von Königen
Title → Titel
Verbalklassen: vereinheitlichen: entweder mit Bindestrich oder ohne; entweder alle mit römischen Zahlen oder alle mit arabischen;
kons → rad
entweder Subklasse und Subkategorie oder Unterklasse und Unterkategorie
Lemma-Wurzel → Wurzel

Teilwörterbuch ist auch nicht passend. Jedoch fehlt mir hier die treffende Bezeichnung.

**Comment by dwerning** [comment]
Auch Sortierfolge im Blick haben: Nisben von A, Nisben von B, Adverbien von A, ...

**Comment by dwerning** [comment]
Vgl. auch "BC/AD" vs. "BCE/CE" in https://github.com/thesaurus-linguae-aegyptiae/tla-web/issues/53

**Comment by dwerning** [comment]
Vgl. auch https://github.com/thesaurus-linguae-aegyptiae/tla-web/issues/72
