### ISSUE TITLE
Suchergebnis-Seite: Wiederholung der Suchanfrage fehlt

### ISSUE THREAD

**Issue by simondschweitzer** [thesaurus-linguae-aegyptiae/tla-web#70]
Nutzen: der User weiß (sieht sofort), wonach er gesucht hat
Abbildung der Suchparameter gemäß Planung vgl. https://github.com/JKatzwinkel/tla-dev-doc/raw/master/design/wireframes/03a_trefferliste_wort.png

**Comment by dwerning** [comment]
Im Prototyp schon umgesetzt:
![grafik](https://user-images.githubusercontent.com/33833393/123323514-e496c080-d535-11eb-8f80-0d27af94bf86.png)

**Comment by dwerning** [comment]
Nachfolge-ToDo: #185
