### ISSUE TITLE
Suchergebnis-Seite: default-Sortierung fehlt

### ISSUE THREAD

**Issue by simondschweitzer** [thesaurus-linguae-aegyptiae/tla-web#71]
- Defaultsortierung fehlt
- Sortieroption "nach Wortart" fehlt, vgl. https://github.com/JKatzwinkel/tla-dev-doc/blob/master/design/frames.md
- inkonsequente Anwendung der Optionen "aufsteigend" und "absteigend" → entweder immer oder nie

**Comment by simondschweitzer** [comment]
Die Sortierung, die man direkt erhält, ist anscheinend eine alphabetische (!) anhand der Lemmanummern.

**Comment by simondschweitzer** [comment]
![image](https://user-images.githubusercontent.com/16794796/112332244-e0020800-8cb9-11eb-8524-6bc821f2322d.png)

**Comment by dwerning** [comment]
ToDo:

- Ägyptologische Reihenfolge umsetzen; Sortierfolge 
``` '*' > '=' > '.' > '-' > 'ʾ' > 'ꜣ' > 'a' > 'i' > 'i̯' > 'ı͗' > 'j' > 'ï' > 'y' > 'ꜥ' > 'e' > 'u̯' > 'w' > 'b' > 'p' > 'f' > 'm' > 'n' > 'r' > 'l' > 'h' > 'ḥ' > 'ḫ' > 'h̭' > 'ẖ' > 'z' > 's' > 'ś' > 'š' > 'q' > 'ḳ' > 'k' > 'g' > 't' > 'ṱ' > 'ṯ' > 'č' > 'd' > 'ṭ' > 'ḏ' > 'č̣' ```

- ggf. danach Feinjustierung => mit DW zu besprechen

**Comment by dwerning** [comment]
Wird eine Suche ausgeführt, so wird per default **gar nicht** sortiert.
Man kann dies schnell überprüfen, indem man "&sort=sortKey_asc" an die URL dran hängt, z.B.
* ohne: http://localhost:8080/search/lemma?script=hieratic&_script=on&_script=on&transcription=nfr&transcription_enc=unicode&wordClass.type=excl_names&root=&root_enc=unicode&translation.text=&translation.lang=de&bibliography=
* mit: http://localhost:8080/search/lemma?script=hieratic&_script=on&_script=on&transcription=nfr&transcription_enc=unicode&wordClass.type=excl_names&root=&root_enc=unicode&translation.text=&translation.lang=de&bibliography=&sort=sortKey_asc 

Auf der Suchergebnisseite muss also **im Falle eines fehlenden URL/GET-Parameters** "&sort=" dafür gesorgt werden, dass überhaupt sortiert wird (dann default: alphabetisch, aufsteigend).
