### ISSUE TITLE
Suchergebnis-Seite: (un)mögliche Hierarchisierung der Treffer

### ISSUE THREAD

**Issue by simondschweitzer** [thesaurus-linguae-aegyptiae/tla-web#74]
Crossreferenzen von obsoleten auf reguläre Lemmata und hierarchische Über- und Unterordnungen müssen in der Trefferliste zusammengruppiert werden. vgl. https://github.com/JKatzwinkel/tla-dev-doc/raw/master/design/wireframes/03a_trefferliste_wort.png

**Comment by dwerning** [comment]
Letzer Stand war, dass Nesting zu dem Problem führt, dass genestete Ergebnis-Elemente nur dort, nicht mehr am eigentlichen Ort der alphabetischen Sortierung auftauchen, dort 'vermisst'. Vieleicht gibt es ein Subset (z.B. "jri (sxr)" unter "jri"; obsoletes "zS" unter "zxA") für das das Nesting _immer_ unproblematisch ist. 
Siehe dazu: https://github.com/thesaurus-linguae-aegyptiae/tla-webdesign-prototype/issues/43
