### ISSUE TITLE
Bezeichnungen: Lemma-Seite

### ISSUE THREAD

**Issue by simondschweitzer** [thesaurus-linguae-aegyptiae/tla-web#76]
Geprüft → Regulär (o.ä.)
Wörterbuch-Eintrag → Lemmadetailansicht (o.ä.)
AutorIn → Autor
EditorIn → Editor(en)
Revisionsstatus → Redaktionsstatus
Letzte Revision → Letzte Änderung
Teile → Bestandteile
Teil von → Bestandteil von
Untergeordnet → Hierarchisch untergeordnet
Übergeordnet → Hierarchisch übergeordnet

Bezeugung und Textvorkommen sind mir unverständlich.

**Comment by dwerning** [comment]
Vgl. auch "BC/AD" vs. "BCE/CE" in #53

**Comment by dwerning** [comment]
Geprüft → Verifiziert
Noch nicht geprüft → Noch nicht verifiziert
Obsolete → Inaktiv
