### ISSUE TITLE
Suchseite (=Wireframe 2a): Auswahl der Wortarten

### ISSUE THREAD

**Issue by simondschweitzer** [thesaurus-linguae-aegyptiae/tla-web#77]
Der Eintrag "Wurzel" ist zuviel. Mit dieser Suchseite wird nach Lemmata gesucht, nicht nach Wurzeln. Insofern ist der Eintrag zu streichen.

**Comment by dwerning** [comment]
cf. https://github.com/thesaurus-linguae-aegyptiae/tla-web/issues/64
