### ISSUE TITLE
Hilfe-Struktur: globale Navigationsleiste

### ISSUE THREAD

**Issue by simondschweitzer** [thesaurus-linguae-aegyptiae/tla-web#82]
Die Hilfeseite sollte kontextbezogen sein und nicht von jedem Startpunkt gleich, vgl. <https://github.com/JKatzwinkel/tla-dev-doc/blob/master/design/02_karteikarten.md#globales-menu> und <https://github.com/JKatzwinkel/tla-dev-doc/blob/master/design/frames.md>

**Comment by dwerning** [comment]
Fraglich ob globales Menü seitensensitiv sein kann; ggf. seitenbezogene Hilfe als icon #44.

**Comment by dwerning** [comment]
Struktur aufgebaut; parallel: 
- help-Icon auf Seite
- Menü mit Verzeichnis der Hilfeseiten
