### ISSUE TITLE
Hilfe-Inhalte: globale Navigationsleiste

### ISSUE THREAD

**Issue by simondschweitzer** [thesaurus-linguae-aegyptiae/tla-web#83]
Die Konzeption, dass Help kontextbezogen ist (vgl. #82 ), beißt sich mit der Anlage von Unterpunkten wie BTS Glossierung oder Linguistische Glossierung. Folgt man der Unterpunktstrategie wird sich eine größere Anzahl an Dokumenten hier einfinden, wie z.B. bibliographische Abkürzungen, sodass die Auswahlliste unübersichtlich wird. Ferner sind solche Dokumente ihrem Wesen nach von Hilfeseiten verschieden. Könnte man evtl. diese Informationsdokumente hier auslagern? Z.B. in die Info-i's? Oder unter Extras? Dort sollen ja auch die bibliographischen Abkürzungen erscheinen, sodass die Glossierungsinfos dort auch gut passen würden.

**Comment by dwerning** [comment]
#39 
#45

**Comment by dwerning** [comment]
Listen in Menüpunkt Extras/Listings verschoben
