### ISSUE TITLE
Lemma-Seite: Ansicht bei fehlenden Attributwerten, insb. Hieroglyphen

### ISSUE THREAD

**Issue by simondschweitzer** [thesaurus-linguae-aegyptiae/tla-web#86]
Hat ein Lemma keine Hieroglyphencodes, wie bspw. alle demotischen Lemmata, erscheint ein weißer Leerraum zwischen zwei horizontalen Strichen. Besser wäre es, wenn das Feld gar nicht erscheint; jedenfalls erscheint es bei den demotischen Lemmata sinnvoll, dass kein Freiraum für Information freigehalten wird, der für die demotischen Lemmata keinen Sinn ergibt.
Ob man aber Bezeugung / Textvorkommen ausblenden soll, wenn keine Belege vorliegen, ist diskutabel.

**Comment by dwerning** [comment]
Status:

1. Mit Hieroglyphen
![grafik](https://user-images.githubusercontent.com/33833393/123285294-3414c680-d50d-11eb-8fcd-79702bb0c77a.png)

2. Fehlende Hieroglyphen (im BTS noch keine eingetragen)
![grafik](https://user-images.githubusercontent.com/33833393/123284970-f3b54880-d50c-11eb-99e1-f5b8247b08c3.png)

3. Demotisch: _immer_ keine Hieroglyphen
![grafik](https://user-images.githubusercontent.com/33833393/123285423-527ac200-d50d-11eb-9f0b-ed3717acb4a0.png)

Ziel:
1. Mit Hieroglyphen: so wie es ist
2. Fehlende Hieroglyphen (im BTS noch keine eingetragen): "Hieroglyphische Schreibung: _keine eingetragen_" (genauer Wortlaut noch zu überlegen)
3. Demotisch: Lücke schließen / Trennstrich ausblenden

**Comment by simondschweitzer** [comment]
Soll der zweite Punkt die allgemeine Strategie sein? D.h. soll stets bei Feldern, in denen es keine Informationen gibt, ein solcher Dummytext stehen? Soll dann also in vielen Fällen stehen: Nominalbildungsklasse Osing: nicht angegeben o.ä.?

**Comment by dwerning** [comment]
Fehlt/Leer-Hinweis vorerst nur bei wirklichen Fehlstellen (z.B. hieroglyphischer Nennschreibung), nicht bei fehlender Nominalklasse (insb. natürlich nicht, wenn es kein Nomen ist).

**Comment by dwerning** [comment]
ohne Hinweis bei fehlernden Hieroglyphen (s.o. 2)
