### ISSUE TITLE
Trefferseite (=Wireframe 3a): Problem mit Nicht-ASCII-Zeichen bei Suche modifizieren

### ISSUE THREAD

**Issue by simondschweitzer** [thesaurus-linguae-aegyptiae/tla-web#88]
Führt man eine Suche mit Nicht-ASCII-Zeichen bei Transkription oder Übersetzung aus (bei Bibliographie geht dies nicht, vgl. #84), und drückt dann Suche modifizieren, wird in das Suchfeld nicht das Nicht-ASCII-Zeichen eingetragen, sondern dessen URL-Encoded Character. Sucht man dann erneut, entstehen andere Treffer.
Beispiel:

- Suche nach fnḏ
- Suche modifizieren produziert ein fn%E1%B8%8F
- Erneute Suche produziert andere Treffer (als ob man nach fn sucht)

**Comment by JKatzwinkel** [comment]
bereits gefixt in https://github.com/JKatzwinkel/tla-web/commit/c17e6da082bac9f0dc21cffed11b815823d5c115
