### ISSUE TITLE
Trefferseite: Fehler bei Ergebniseintrag mit einer Nummer größer 10000

### ISSUE THREAD

**Issue by RDBloese** [thesaurus-linguae-aegyptiae/tla-web#91]
Bei Wechsel zur Trefferseite mit einem Sucheintrag größer 10000 wirft das Programm einen Fehler. 

https://tla.bbaw.de/search/dict?script=hieroglyphic&script=demotic&transcription=+*&transcription_enc=manuel_de_codage&pos_type=%28any_but_names%29&page=417

**Comment by simondschweitzer** [comment]
Wie in #92 (vgl. https://github.com/thesaurus-linguae-aegyptiae/tla-web/issues/92#issuecomment-863108206) ist das ein Problem des Prototypen, aber nicht von tla-web.
