### ISSUE TITLE
Trefferseite: Ergebnisanzahl auf 10000 begrenzt

### ISSUE THREAD

**Issue by RDBloese** [thesaurus-linguae-aegyptiae/tla-web#92]
Die Ergebnisanzahl ist auf 10000 begrenzt. Es gibt aber mehr gültige Suchergebnisse.
https://tla.bbaw.de/search/dict?script=hieroglyphic&script=demotic&pos_type=%28any_but_names%29

**Comment by simondschweitzer** [comment]
Willkommen beim Wörterbuch und vielen Dank für Ihre ersten Issues! Das Problem, das Sie schildern, betrifft glücklicherweise nur den obsoleten Prototypen, den Sie über tla.bbaw.de ansteuern, aber nicht das eigentliche tla-web. Wenn Sie dort mehr als 10000 Treffer haben, ist das unproblematisch, vgl. http://localhost:8080/lemma/search?script=hieratic&_script=on&script=demotic&_script=on&transcription=&wordClass.type=&root=&translation.text=&_translation.lang=on&_translation.lang=on&_translation.lang=on&bibliography=&anno.type= (Screenshot beigefügt!)
![suche_mehr_als_10000_treffer](https://user-images.githubusercontent.com/16794796/122375865-e673e900-cf63-11eb-8e75-79fba6bccb42.jpg)
Kann das Issue geschlossen werden oder habe ich noch etwas übersehen?

**Comment by schnoepf** [comment]
...obsoleter Prototyp? Und ich mache mir eine Welle, um den ständig am Laufen zu halten? ;)

**Comment by JKatzwinkel** [comment]
naja die teure nginx schulung soll sich ja schlieszlich lohnen!
