### ISSUE TITLE
Copy Citation-Funktion (verschiedene Seiten)

### ISSUE THREAD

**Issue by RDBloese** [thesaurus-linguae-aegyptiae/tla-web#95]
Der Copy Citation Button kopiert lediglich generische Werte

**Comment by dwerning** [comment]
Solltext: vgl. Prototyp


js-Funktion copyStringToClipboard  in: https://github.com/thesaurus-linguae-aegyptiae/tla-webdesign-prototype/blob/eval/webd/static/js/tla-functions.js

Mehrfach eingesetzt (copy IDs, copy citation u.a.m. in Prototyp https://github.com/thesaurus-linguae-aegyptiae/tla-webdesign-prototype/blob/eval/webd/templates/details/lemma.html 
Dort Sollinhalte/Muster einsehbar.

**Comment by dwerning** [comment]
Zuerst/parallel zu lösen: #62

**Comment by RDBloese** [comment]
Gefixed, siehe Branch Issue 95

**Comment by dwerning** [comment]
Kopierfunktion funktioniert aktuell nicht mehr (kein Überschreiben des clipboards)
